# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a165b607e49900572aa0921daaf4a0577a912d6a57b40f0e567e0a301b373ec96b2d560c6d700312bec3c62a794b37feeb4b339173aa94d5036ea7017b6df28

test:
  secret_key_base: 562dd41cc9a85cac17abf37279a048579db33ae071b5079af6bcc54f226d357f7f29bcf1b78f0612bf6078bed6dbee62965b0ce670ebd6a01c8a487d32efa15b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
